DROP TABLE IF EXISTS users;

CREATE TABLE users(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    fullname TEXT NOT NULL,
    photoAddress TEXT NOT NULL,
    birthdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
